version: '2'

services:
    odsupercomponent:
        build: .
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    proxy-miniature-lps-1:
        build: .
        network_mode: "host"
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-lps --cid=${CID} --id=1"
