.\" Manpage for opendlv-proxy-miniature-gpio
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-proxy-miniature-gpio 1 "10 May 2017" "0.2.1" "opendlv-proxy-miniature-gpio man page"

.SH NAME
opendlv-proxy-miniature-gpio \- This module interfaces with an gpio pin at the BeagleBone Black.


.SH SYNOPSIS
.B opendlv-proxy-miniature-gpio --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-proxy-miniature-gpio --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

