.\" Manpage for opendlv-system-miniature-example
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-system-miniature-example 1 "03 January 2017" "0.0.2" "opendlv-system-miniature-example man page"

.SH NAME
opendlv-system-miniature-example \- This module interfaces with an example pin at the BeagleBone Black.


.SH SYNOPSIS
.B opendlv-system-miniature-example --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-system-miniature-example --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

