.\" Manpage for opendlv-sim-miniature-differential
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-sim-miniature-differential 1 "27 April 2017" "0.1.7" "opendlv-sim-miniature-differential man page"

.SH NAME
opendlv-sim-miniature-differential 


.SH SYNOPSIS
.B opendlv-sim-miniature-differential --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-sim-miniature-differential --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

