.\" Manpage for opendlv-proxy-miniature-ps3controller
.\" Author: Björnborg Nguyen <bjornborg.nguyen@chalmers.se>.

.TH opendlv-proxy-miniature-ps3controller 1 "22 June 2017" "0.0.1" "opendlv-proxy-miniature-ps3controller man page"

.SH NAME
opendlv-proxy-miniature-ps3controller \- This tool interfaces with a miniature vehicle.



.SH SYNOPSIS
.B opendlv-proxy-miniature-ps3controller --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-proxy-miniature-ps3controller --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Björnborg Nguyen (bjornborg.nguyen@chalmers.se)

