.\" Manpage for opendlv-proxy-miniature-pwm-motor
.\" Author: Björnborg Nguyen <bjornborg.nguyen@chalmers.se>.

.TH opendlv-proxy-miniature-pwm 1 "02 May 2017" "0.0.1" "opendlv-proxy-miniature-pwm-motor man page"

.SH NAME
opendlv-proxy-miniature-pwm-motor \- This module interfaces with an pwm pin at the BeagleBone blue in order to control motors.


.SH SYNOPSIS
.B opendlv-proxy-miniature-pwm-motor --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-proxy-miniature-pwm-motor --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Björnborg Nguyen (bjornborg.nguyen@chalmers.se)
