.\" Manpage for opendlv-proxy-miniature-ps4controller
.\" Author: Federico Giaimo <giaimo@chalmers.se>.

.TH opendlv-proxy-miniature-ps4controller 1 "15 February 2018" "0.0.1" "opendlv-proxy-miniature-ps4controller man page"

.SH NAME
opendlv-proxy-miniature-ps4controller \- This tool interfaces with a miniature vehicle.



.SH SYNOPSIS
.B opendlv-proxy-miniature-ps4controller --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-proxy-miniature-ps4controller --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.

