.\" Manpage for opendlv-proxy-miniature-analog
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-proxy-miniature-analog 1 "10 May 2017" "0.2.1" "opendlv-proxy-miniature-analog man page"

.SH NAME
opendlv-proxy-miniature-analog \- This module interfaces with an analog pin at the BeagleBone Black.


.SH SYNOPSIS
.B opendlv-proxy-miniature-analog --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-proxy-miniature-analog --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

