.\" Manpage for opendlv-proxy-miniature-pwm
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-proxy-miniature-pwm 1 "27 April 2017" "0.1.7" "opendlv-proxy-miniature-pwm man page"

.SH NAME
opendlv-proxy-miniature-pwm \- This module interfaces with an pwm pin at the BeagleBone Black.


.SH SYNOPSIS
.B opendlv-proxy-miniature-pwm --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-proxy-miniature-pwm --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

