.\" Manpage for opendlv-proxy-miniature-qualisys
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-proxy-miniature-qualisys 1 "10 May 2017" "0.2.1" "opendlv-proxy-miniature-qualisys man page"

.SH NAME
opendlv-proxy-miniature-qualisys \- This module interfaces with an qualisys.


.SH SYNOPSIS
.B opendlv-proxy-miniature-qualisys --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-proxy-miniature-qualisys --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

