.\" Manpage for opendlv-proxy-miniature-sonar-pru
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-proxy-miniature-sonar-pru 1 "02 May 2017" "0.1.9" "opendlv-proxy-miniature-sonar-pru man page"

.SH NAME
opendlv-proxy-miniature-sonar-pru \- This module interfaces with a time-of-flight sensor sensor via the am335x PRU.


.SH SYNOPSIS
.B opendlv-proxy-miniature-sonar-pru --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-proxy-miniature-sonar-pru --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

