.\" Manpage for opendlv-proxy-miniature-lps
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-proxy-miniature-lps 1 "10 May 2017" "0.2.1" "opendlv-proxy-miniature-lps man page"

.SH NAME
opendlv-proxy-miniature-lps \- This module interfaces with an lps pin at the BeagleBone Black.


.SH SYNOPSIS
.B opendlv-proxy-miniature-lps --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-proxy-miniature-lps --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

